"""Business logic for docs/api_spec.md #2/#3/#5: description, chat, chat history.

Description lookups are pure cache reads (data/rag/gold/emuseum/descriptions_by_type.jsonl,
pre-generated by ai/rag/generate_descriptions.py). Chat calls the local LLM in real time,
grounded in the artifact's GOLD context_text plus a short recent-message window.
"""

from __future__ import annotations

import sqlite3

from ai.llm.ollama_client import generate
from ai.rag.gold_store import GoldDataMissing, get_cached_description, get_context_text
from ai.rag.prompts import build_chat_prompt
from backend.db.artifacts import get_artifact
from backend.db.conversations import (
    ArtifactNotFoundError,
    add_message,
    create_conversation,
    get_conversation,
    list_messages,
)
from backend.schemas import (
    ChatHistoryResponse,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    DescriptionRequest,
    DescriptionResponse,
)
from backend.services.classification_service import ApiError


CHAT_MODEL = "exaone3.5:7.8b"
CHAT_HISTORY_TURNS = 3  # 최근 N턴(질문+답변)만 프롬프트에 포함


def fetch_description(
    connection: sqlite3.Connection, payload: DescriptionRequest
) -> DescriptionResponse:
    artifact = get_artifact(connection, payload.artifact_id)
    if artifact is None:
        raise ApiError(
            404,
            "ARTIFACT_NOT_FOUND",
            f"artifact_id '{payload.artifact_id}'에 해당하는 유물을 찾을 수 없습니다.",
        )
    try:
        text = get_cached_description(payload.artifact_id, payload.visitor_type)
    except GoldDataMissing as error:
        raise ApiError(404, "DESCRIPTION_NOT_FOUND", str(error)) from error

    return DescriptionResponse(
        artifact_id=payload.artifact_id,
        artifact_name=artifact["artifact_name"],
        visitor_type=payload.visitor_type,
        description=text,
        sources=[artifact["source"]],
    )


def send_chat_message(connection: sqlite3.Connection, payload: ChatRequest) -> ChatResponse:
    artifact = get_artifact(connection, payload.artifact_id)
    if artifact is None:
        raise ApiError(
            404,
            "ARTIFACT_NOT_FOUND",
            f"artifact_id '{payload.artifact_id}'에 해당하는 유물을 찾을 수 없습니다.",
        )

    if payload.session_id:
        conversation = get_conversation(connection, payload.session_id)
        if conversation is None:
            raise ApiError(
                404,
                "SESSION_NOT_FOUND",
                f"session_id '{payload.session_id}'를 찾을 수 없습니다.",
            )
    else:
        try:
            conversation = create_conversation(
                connection, payload.artifact_id, payload.visitor_type
            )
        except ArtifactNotFoundError as error:
            raise ApiError(
                404,
                "ARTIFACT_NOT_FOUND",
                f"artifact_id '{payload.artifact_id}'에 해당하는 유물을 찾을 수 없습니다.",
            ) from error

    try:
        context_text = get_context_text(payload.artifact_id)
    except GoldDataMissing as error:
        raise ApiError(404, "ARTIFACT_CONTEXT_NOT_FOUND", str(error)) from error

    recent = list_messages(connection, conversation.session_id, limit=CHAT_HISTORY_TURNS * 2)
    history = [(message.role, message.content) for message in recent]

    prompt = build_chat_prompt(context_text, payload.visitor_type, payload.question, history)
    response = generate(prompt, CHAT_MODEL)
    answer = response.get("response", "").strip()

    add_message(connection, conversation.session_id, "user", payload.question)
    add_message(connection, conversation.session_id, "assistant", answer)

    return ChatResponse(
        session_id=conversation.session_id,
        artifact_id=payload.artifact_id,
        visitor_type=payload.visitor_type,
        answer=answer,
        sources=[artifact["source"]],
    )


def fetch_chat_history(connection: sqlite3.Connection, session_id: str) -> ChatHistoryResponse:
    conversation = get_conversation(connection, session_id)
    if conversation is None:
        raise ApiError(404, "SESSION_NOT_FOUND", f"session_id '{session_id}'를 찾을 수 없습니다.")

    messages = list_messages(connection, session_id)
    return ChatHistoryResponse(
        session_id=conversation.session_id,
        artifact_id=conversation.artifact_id,
        visitor_type=conversation.visitor_type,
        messages=[ChatMessage(role=message.role, content=message.content) for message in messages],
    )
